services:
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"               # http://localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports: ["5433:5432"]        # host->container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000", "9001:9001"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - miniodata:/data

  mc:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 minio minio123 &&
      mc mb -p local/app-bucket || true &&
      mc anonymous set download local/app-bucket
      "
    restart: "no"

  # ---- kept exactly as notes (original lines) ----
  # name: API tests (Jest)
  # run: npm -w apps/api run test -- --runInBand
  # name: Web build (for Playwright)
  # run: npm -w apps/web run build
  # name: Install Playwright browsers
  # run: npm -w apps/web run playwright:install
  # name: Web E2E (Playwright)
  # run: npm -w apps/web run test:e2e
  #
  # same content also preserved below as labels so file stays valid:
  ci_notes:
    image: alpine:3.20
    command: ["sh","-c","sleep infinity"]
    labels:
      - "name: API tests (Jest)"
      - "run: npm -w apps/api run test -- --runInBand"
      - "name: Web build (for Playwright)"
      - "run: npm -w apps/web run build"
      - "name: Install Playwright browsers"
      - "run: npm -w apps/web run playwright:install"
      - "name: Web E2E (Playwright)"
      - "run: npm -w apps/web run test:e2e"

volumes:
  pgdata:
  miniodata:
  pgadmin:
