# 1. Base image with dependencies
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
COPY apps/web/package*.json ./apps/web/
RUN npm ci

# 2. Build stage
FROM node:20-alpine AS builder
WORKDIR /app
COPY . .
RUN npm ci
ENV NODE_ENV=production
RUN npm run build -w apps/web

# 3. Runtime
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

# Copy build output from builder
COPY --from=builder /app/apps/web/.next ./apps/web/.next
#COPY --from=builder /app/apps/web/public ./apps/web/public
COPY --from=builder /app/apps/web/package.json ./apps/web/package.json

EXPOSE 3000
CMD ["npx","--yes","next","start","apps/web","-p","3000"]
