name: CI
on:
  push:
    branches: [ main ]
  pull_request:
permissions:
  actions: read
  contents: read
jobs:
  nx-ci:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NjU2YmY2NWUtOGYyYi00M2Q0LWE5Y2EtZTNjOTgxMmUwNTg5fHJlYWQtd3JpdGU= }}  # 👈 inject token
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch: main

      # optionally start distributed agents if you use them
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      - run: npx nx affected -t lint test build
      - if: always()
        run: npx nx fix-ci
