name: Build & Push Docker images

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ toLower(github.repository_owner) }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push API
        uses: docker/build-push-action@v6
        with:
          context: .                           # 👈 monorepo root
          file: docker/dev/Dockerfile.api      # 👈 path to your API Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/api:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/api:${{ github.run_number }}

      - name: Build & push Web
        uses: docker/build-push-action@v6
        with:
          context: .                           # 👈 monorepo root
          file: docker/dev/Dockerfile.web      # 👈 path to your Web Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/web:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/web:${{ github.run_number }}
